create table if not exists deckaura.lead_magnet_leads (
  id bigint generated by default as identity primary key,
  asset_slug text not null,
  email text not null,
  email_hash text not null,
  source_page text not null,
  locale text,
  marketing_consent boolean not null default false,
  consent_version text not null,
  consented_at timestamptz,
  first_download_at timestamptz not null default clock_timestamp(),
  last_download_at timestamptz not null default clock_timestamp(),
  download_count integer not null default 1,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  retention_expires_at timestamptz not null,
  created_at timestamptz not null default clock_timestamp(),
  updated_at timestamptz not null default clock_timestamp(),
  constraint lead_magnet_leads_asset_slug_check
    check (asset_slug ~ '^[a-z0-9][a-z0-9-]{2,80}$'),
  constraint lead_magnet_leads_email_hash_check
    check (email_hash ~ '^[a-f0-9]{64}$'),
  constraint lead_magnet_leads_download_count_check
    check (download_count > 0),
  constraint lead_magnet_leads_asset_email_key
    unique (asset_slug, email_hash)
);

create index if not exists lead_magnet_leads_marketing_idx
  on deckaura.lead_magnet_leads (created_at desc)
  where marketing_consent;

create index if not exists lead_magnet_leads_retention_idx
  on deckaura.lead_magnet_leads (retention_expires_at);

create table if not exists deckaura.lead_magnet_download_events (
  id uuid primary key default gen_random_uuid(),
  lead_id bigint not null references deckaura.lead_magnet_leads(id) on delete cascade,
  asset_slug text not null,
  ip_hash text not null,
  user_agent_hash text not null,
  referrer_host text,
  created_at timestamptz not null default clock_timestamp(),
  retention_expires_at timestamptz not null default (clock_timestamp() + interval '45 days'),
  constraint lead_magnet_download_events_ip_hash_check
    check (ip_hash ~ '^[a-f0-9]{64}$'),
  constraint lead_magnet_download_events_user_agent_hash_check
    check (user_agent_hash ~ '^[a-f0-9]{64}$')
);

create index if not exists lead_magnet_download_events_ip_created_idx
  on deckaura.lead_magnet_download_events (ip_hash, created_at desc);

create index if not exists lead_magnet_download_events_lead_idx
  on deckaura.lead_magnet_download_events (lead_id);

create index if not exists lead_magnet_download_events_retention_idx
  on deckaura.lead_magnet_download_events (retention_expires_at);

alter table deckaura.lead_magnet_leads enable row level security;
alter table deckaura.lead_magnet_download_events enable row level security;

create policy "Block direct lead magnet lead access"
  on deckaura.lead_magnet_leads
  for all to anon, authenticated
  using (false)
  with check (false);

create policy "Block direct lead magnet event access"
  on deckaura.lead_magnet_download_events
  for all to anon, authenticated
  using (false)
  with check (false);

revoke all on table deckaura.lead_magnet_leads from anon, authenticated;
revoke all on table deckaura.lead_magnet_download_events from anon, authenticated;
revoke all on sequence deckaura.lead_magnet_leads_id_seq from anon, authenticated;

comment on table deckaura.lead_magnet_leads is
  'Server-only lead records for downloadable Deckaura learning resources.';
comment on table deckaura.lead_magnet_download_events is
  'Privacy-preserving, short-retention download events used for abuse prevention.';
